export const SET_LOADING = "SET_LOADING";
export const SET_READY = "SET_READY";
export const SHOW_SUCCESS_NOTICE = "SHOW_SUCCESS_NOTICE";
export const SHOW_ERROR_NOTICE = "SHOW_ERROR_NOTICE";
export const SHOW_WARNING_NOTICE = "SHOW_WARNING_NOTICE";
export const CLOSE_NOTICE = "CLOSE_NOTICE";