export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const SET_PLAYLIST = "SET_PLAYLIST";
export const SET_TOGGLE = "SET_TOGGLE";
export const SET_TOGGLE_REMOVE = "SET_TOGGLE_REMOVE";
export const SET_TOGGLE_REMOVE_SONG = "SET_TOGGLE_REMOVE_SONG";
export const SET_TOGGLE_SERVICE = "SET_TOGGLE_SERVICE";